apiVersion: v1
kind: Secret
metadata:
    name: nasbackup-secrets
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:QNApntTDcQ==,iv:qlY3/vVHhmUWDgKoGJpMRtXUisMAEfm97sAhzdb8m04=,tag:E1cSsJGLkvMTRh41sNgBpw==,type:str]
    KOPIA_CHECK_FOR_UPDATES: ENC[AES256_GCM,data:AWNoHc0=,iv:nYTYfp1P9nC0hiQHyqS1YNSovXqGekHLH6ZpDKv8x+M=,tag:mIi9gQaPIkj9Mtoq3nCqfg==,type:str]
sops:
    age:
        - recipient: age10mxrc4xzc0udh8ra304ftjnc6m3x3qfe60qulu8j9eqjhrgkns9qnk50up
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSzRxZytJSEhha1VBVDRP
            R2NuRlIvWEhGUTRUR3pqbWRsaFRodUMyWFRFClIzUCtBNnd1YzZScFZ5R295TzNj
            Zy81ZW50RHJtd0pFUFJYUTc5aWlJQ0EKLS0tIHNiUjJrYUFrdmN3TzZBNVBUcjVZ
            NlA3SUE3RkRET2ZSVXpVeHRiS0lMK3cK3zm0DMtpcLBC63GAZ+Hdr/fRnMNUZUpM
            +MZqboraCDTZs/KtCPaeRK41ix7RNHsIuX5A7sqWXalXP6HGlxLVQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T10:51:06Z"
    mac: ENC[AES256_GCM,data:zNMwolCqPcaqbMKMcZPx4P838YxY6V+mY/hNHBiDM2DdakpKmSbjCFoZhudUslzULn3EN6hkEi0dJICfkuZ49xKjhItaI0QNaM0WMF1U6k302msMqRhDYs7cpsDSGH1sO1rtE9oVTLE5ELWkbCNje4Ybqfs4/2zXHEaRN5bHhbg=,iv:4sCZe6NhNAdOEK2eo5+2cAVZx0QQ18Y3GpD3se+UsCw=,tag:gjg+gr3ZUC+i2n0PrSKuDQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
