apiVersion: v1
kind: Secret
metadata:
    name: nasbackup-secrets
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:y1O5OpGHsg==,iv:G6FhjK4oB24t9xZLtAhFv4M62d5eW6Q/ySOjg7lLtNM=,tag:JB0d8pcyZrrn6xlfNwbeuA==,type:str]
sops:
    age:
        - recipient: age10mxrc4xzc0udh8ra304ftjnc6m3x3qfe60qulu8j9eqjhrgkns9qnk50up
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSzRxZytJSEhha1VBVDRP
            R2NuRlIvWEhGUTRUR3pqbWRsaFRodUMyWFRFClIzUCtBNnd1YzZScFZ5R295TzNj
            Zy81ZW50RHJtd0pFUFJYUTc5aWlJQ0EKLS0tIHNiUjJrYUFrdmN3TzZBNVBUcjVZ
            NlA3SUE3RkRET2ZSVXpVeHRiS0lMK3cK3zm0DMtpcLBC63GAZ+Hdr/fRnMNUZUpM
            +MZqboraCDTZs/KtCPaeRK41ix7RNHsIuX5A7sqWXalXP6HGlxLVQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-10T17:32:22Z"
    mac: ENC[AES256_GCM,data:qBUbbpdfhmQovkxF0EJYtz6HWKLcmUB03QCUzk6UqPs+UmSNyvz8yNh38fq0IHX8KTfVVRbXSKmYWVKRmqHjot6DK93Aqb6aN8HYhCZFq2Z+pp8CDRr4mgXfoQOR+eE5W9J+S2LvFKvTbZgDx074yx6jYGbigIUemeEBxQHpRSE=,iv:yEFC+Cvh/+MFbWryO/OlA8G3YiCHnk3AbJA1fy8fGjU=,tag:9MCvzKnp1BMtarMPsepBsw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
