apiVersion: v1
kind: Secret
metadata:
    name: nasbackup-secrets
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:QNApntTDcQ==,iv:qlY3/vVHhmUWDgKoGJpMRtXUisMAEfm97sAhzdb8m04=,tag:E1cSsJGLkvMTRh41sNgBpw==,type:str]
    KOPIA_CHECK_FOR_UPDATES: ENC[AES256_GCM,data:L51ld3o=,iv:dsSqWYq51WSztDZvvqT4mWCOSVQsotCq36qRaHI2Qkc=,tag:dA+U6gef9eiUCvqG72sfSA==,type:bool]
sops:
    age:
        - recipient: age10mxrc4xzc0udh8ra304ftjnc6m3x3qfe60qulu8j9eqjhrgkns9qnk50up
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSzRxZytJSEhha1VBVDRP
            R2NuRlIvWEhGUTRUR3pqbWRsaFRodUMyWFRFClIzUCtBNnd1YzZScFZ5R295TzNj
            Zy81ZW50RHJtd0pFUFJYUTc5aWlJQ0EKLS0tIHNiUjJrYUFrdmN3TzZBNVBUcjVZ
            NlA3SUE3RkRET2ZSVXpVeHRiS0lMK3cK3zm0DMtpcLBC63GAZ+Hdr/fRnMNUZUpM
            +MZqboraCDTZs/KtCPaeRK41ix7RNHsIuX5A7sqWXalXP6HGlxLVQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-10T22:52:14Z"
    mac: ENC[AES256_GCM,data:/zz1DqQ6XeLL//4OV7FbDYWkkmAsja8w4ryy7NniS/c9MybM7i7ERwwgjVyXRMJ7YuNX6884kRQjkL8jxn09B0cbAo/KmMFLPKhVLC7E+8wS/wwISKSTAMHLcUfkqSreeJYes0XjoIpw8yhIpMvttr3qdnKCeAkdxNtgH51HPqc=,iv:SSoiULWKjutK00Ft2KBdhFyOqVoMIWeRU31BhYA7T2o=,tag:KEPLKkrwtsbCGoPHvx3F3w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
