---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app victoria-metrics-operator
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    operator:
      enable_converter_ownership: true
    serviceMonitor:
      enabled: true
    podLabels:
      ingress.samoth.eu/kube-apiserver: allow
      egress.samoth.eu/kube-apiserver: allow