apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
type: Opaque
stringData:
  api-token: ENC[AES256_GCM,data:wiQeMMOjtzxkRAbLxAqKNpJSB1HzZ4TFzfkEewsuKBTw+cK7VkuBJg==,iv:TqOF9UDpg2mrbNBKwEF7lELdOUQ3uF6e4u9aA7arcHg=,tag:Rxq7jkLwlMK3b+qoTYq+1Q==,type:str]
sops:
  age:
    - recipient: age10mxrc4xzc0udh8ra304ftjnc6m3x3qfe60qulu8j9eqjhrgkns9qnk50up
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQ2RWcVBZNktyTkppbnRH
        V2VWTjJTeS9ieC8vRjFlclNnQmM1NUxkdm1rCjM5eEFiMUl3RU90Q1UwZkJudTRO
        NWxRRlFzaWJRRUx0c2NqYzF5NWNUZ0kKLS0tIGFJYjc0ZEowRFhpeE5tU3NVeWpP
        MUFRT1JFKytmbzdadkJycGE4UVhyMlEKXxn3K8wAYeduMxjuj93aISgMrJXyaI/z
        SICscUCrucVoOEEQmsL/jtUWUidRpMRizzDS+kEuStcJvs5u19NHgA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-01T17:01:37Z"
  mac: ENC[AES256_GCM,data:LQOO0+H+YwzcM9GkPI6JkcGzRezynk+t7ejjV2togF/FyaAW/KYgJUNsoMs2mv0J7pPEfJHhMehVUWL2LZTJIn4695uFQny7esgusRASCdL9Akx+YIoRuZw81BWhWaXZ8ShKwdFrD16ieKr7B7zEywGHoQO9HXDom16Xpha3XHA=,iv:YK0ZLMw8G714uLeh06C/zDPwbVA652n7PktfEEaVlN4=,tag:mAmhAHvuBkTHFnWHrs0SgQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
