- name: install nut
  package:
    name: nut
    state: latest

- name: copy configs files
  template:
    src: "{{ item }}.j2"
    dest: "/etc/nut/{{ item }}"
    owner: root
    group: nut
    mode: u=rw,g=r
  with_items:
    - nut.conf
    - ups.conf
    - upsd.conf
    - upsd.users
    - upsmon.conf
  notify: restart nut

- name: config ufw - allow ports
  ufw:
    rule: allow
    port: "{{item.port}}"
    proto: "{{item.proto}}"
    comment: nut
  with_items:
    - {"port": 3493, "proto": "tcp"}
    - {"port": 3493, "proto": "udp"}
