experimental_monorepo_root = true

[settings]
task.monorepo_depth = 3  # Only search 3 levels deep

[tools]
"aqua:FiloSottile/age" = "latest"
"aqua:fluxcd/flux2" = "latest"
"aqua:getsops/sops" = "latest"
"aqua:kubernetes/kubectl" = "latest"
"aqua:siderolabs/talos" = "latest"
