---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ocirepository.yaml
  - ./webhook.sops.yaml
  - ./helmrelease.yaml
  - ./netpol.yaml
  - ./grafanadashboard.yaml
  - ./grafanadatasource.yaml