---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cilium.io/ciliumclusterwidenetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: vmagent
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: vmagent
      app.kubernetes.io/component: monitoring
  egress:
    - toEndpoints:
        - matchLabels:
            ingress.samoth.eu/vmagent: allow
    - toEntities:
        - host
      toPorts:
        - ports:
            # etcd
            - port: "2381"
              protocol: TCP
            - port: "2381"
              protocol: UDP
            # kubeapi
            - port: "6443"
              protocol: TCP
            - port: "6443"
              protocol: UDP
            # node-exporter
            - port: "9100"
              protocol: TCP
            - port: "9100"
              protocol: UDP
            # cilium metrics
            - port: "9962"
              protocol: TCP
            - port: "9962"
              protocol: UDP
            # cilium operator metrics
            - port: "9963"
              protocol: TCP
            - port: "9963"
              protocol: UDP
            # hubble metrics
            - port: "9965"
              protocol: TCP
            - port: "9965"
              protocol: UDP
            # kubelet
            - port: "10250"
              protocol: TCP
            - port: "10250"
              protocol: UDP
            # kube-controller-manager
            - port: "10257"
              protocol: TCP
            - port: "10257"
              protocol: UDP
            # kube-scheduler
            - port: "10259"
              protocol: TCP
            - port: "10259"
              protocol: UDP
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: vmalert
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: vmalert
      app.kubernetes.io/component: monitoring
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: vmsingle
            app.kubernetes.io/component: monitoring
  egress:
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: vmsingle
            app.kubernetes.io/component: monitoring
        - matchLabels:
            app.kubernetes.io/name: vmalertmanager
            app.kubernetes.io/component: monitoring
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: vmsingle
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: vmsingle
      app.kubernetes.io/component: monitoring
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: vmalert
            app.kubernetes.io/component: monitoring
        - matchLabels:
            egress.samoth.eu/victoria-metrics: allow
  egress:
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: vmalert
            app.kubernetes.io/component: monitoring
            
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: vmalertmanager
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: vmalertmanager
      app.kubernetes.io/component: monitoring
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: vmalert
            app.kubernetes.io/component: monitoring
        - matchLabels:
            egress.samoth.eu/alert-manager: allow