---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cilium.io/ciliumclusterwidenetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: vmagent-to-metrics-endpoints
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: vmagent
      app.kubernetes.io/component: monitoring
  egress:
    - toEndpoints:
        - matchLabels:
            ingress.samoth.eu/vmagent: allow
    - toEntities:
        - host
      toPorts:
        - ports:
            # kubeapi
            - port: "6443"
              protocol: TCP
            - port: "6443"
              protocol: UDP
