apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:kL+/AzfALC8YSg4K5m9g,iv:yW1HCt4erzOhEXW72eaaCstw4ppoT2OQZsjDr71a6es=,tag:zYZfVs+gCAlflSxRKJt0Sg==,type:str]
    SECRET_CIDR_LAN: ENC[AES256_GCM,data:aHfHwCCdwAKC+nfKrwU=,iv:M08olt3IBeH2pooCATkKgZVcQnACTiKGWAju2CEAppA=,tag:+ZBpKTW3MxJmk2O4NIQfjg==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:7sy1KOT4XDZuh8dmWt4=,iv:0OEhuQzvXv/boEuxioVq396fo580IH6vHt8uWYQxBDI=,tag:AF8Rn9kTLiErKZk+vfmomQ==,type:str]
sops:
    age:
        - recipient: age10mxrc4xzc0udh8ra304ftjnc6m3x3qfe60qulu8j9eqjhrgkns9qnk50up
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZYjFHd3hodnFVaG14Q0RK
            eUR3NHh4TXZ2U1BIck9BOXU4UG4wdzljWHdrCjJTb1p3d01ZSWxGNEtCMms0MG96
            N0R0MnFGczJ4M2NRNlFYZi9hVDY5L2sKLS0tIDA3TEM2TkNuNWRMM3JpUVR3dm8y
            SXdUSUFhN0c0ZWljOUovZHNVVGcvOVUKb3bl/Do5fX5SmCUMOmUVwYu+HQb0FCfH
            0mmi1whQL6Nb7SdwPD2IUlBSsI2r6E6n/OT3f+GmlOjTyysi+cgqbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T16:10:27Z"
    mac: ENC[AES256_GCM,data:YMMPFz0+olc3uzKxYe0gBWv98MxC3uY4EfQliTASoeJ9aPYprC/AXBLiOn0tyJG+3csbxri6aT5bbnhrq4bvzU+Fa4eecwi5i8gH1f5W960RvTuPyeUm+E0nte2o+GLcYHmteyeo5Qui1bedqzFKk7Sr+ATjOTeu6L9R6oI4lF8=,iv:hrBcPXGH3qAPE96GhLYa/lCXUfaarrBk4PrZSWd3BE4=,tag:2Zd9ZZoRxH+eNIi7z0KvYQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
