apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:kL+/AzfALC8YSg4K5m9g,iv:yW1HCt4erzOhEXW72eaaCstw4ppoT2OQZsjDr71a6es=,tag:zYZfVs+gCAlflSxRKJt0Sg==,type:str]
    SECRET_CIDR_LAN_V4: ENC[AES256_GCM,data:s//rhVIEp5LAFrHrzjo=,iv:GxR9Eqy3QTLY9D+elmvB87hcaCQNgdO2W4W5s5PUdeE=,tag:r1vyoY77C0lJ/zges78MEQ==,type:str]
    SECRET_CIDR_LAN_V6: ENC[AES256_GCM,data:AFYjytv5VIeV9r3JJSKwgo4mymIKkA==,iv:du52G4o9WDJp3c4oTzeZSJhnXx9L+uV32rr21b072NY=,tag:3vgQzk+9RvobsHSu9cDVNg==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:7sy1KOT4XDZuh8dmWt4=,iv:0OEhuQzvXv/boEuxioVq396fo580IH6vHt8uWYQxBDI=,tag:AF8Rn9kTLiErKZk+vfmomQ==,type:str]
    SECRET_LB_POOL_IPV4: ENC[AES256_GCM,data:+EnPzHEYWqh5xLwtUVY=,iv:26ZqnwpPgMgCT57C6UNt6k2uu2Kh+wWjkkng4Va/6ts=,tag:CmIsSCyajE8XuSfo0XdedQ==,type:str]
    SECRET_LB_POOL_IPV6: ENC[AES256_GCM,data:eB7nyAnFSxAliLPQF4J43K99mxSAYQW4,iv:WwF5dRSBOD/eF63x65eVu5ksQKYqibyBfNhxXZx5Uwo=,tag:n53+2cNHLjxNod5Da0zUbA==,type:str]
    SECRET_LB_IPV4: ENC[AES256_GCM,data:UoXkizUvdosgip4=,iv:/Or1StmxB0W19ypPSVCFWRnqsDR/VYkQOXceGEnOb/E=,tag:RwouAtohRqCf/X3bXabIHg==,type:str]
    SECRET_LB_IPV6: ENC[AES256_GCM,data:5uNaJ/oJjOXKvlIHkQsTCKP13KI=,iv:flKh9+MJP9qGHJ4dHDJ/W40U4iPCTZFZY/Htn6+iYAg=,tag:XV4OP2dBTvQ/ZoYdUzbvyw==,type:str]
sops:
    age:
        - recipient: age10mxrc4xzc0udh8ra304ftjnc6m3x3qfe60qulu8j9eqjhrgkns9qnk50up
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZYjFHd3hodnFVaG14Q0RK
            eUR3NHh4TXZ2U1BIck9BOXU4UG4wdzljWHdrCjJTb1p3d01ZSWxGNEtCMms0MG96
            N0R0MnFGczJ4M2NRNlFYZi9hVDY5L2sKLS0tIDA3TEM2TkNuNWRMM3JpUVR3dm8y
            SXdUSUFhN0c0ZWljOUovZHNVVGcvOVUKb3bl/Do5fX5SmCUMOmUVwYu+HQb0FCfH
            0mmi1whQL6Nb7SdwPD2IUlBSsI2r6E6n/OT3f+GmlOjTyysi+cgqbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-02T17:12:14Z"
    mac: ENC[AES256_GCM,data:OV4D0Pkbi7fUDEkuMX5x3C4i8KJWp56+OR/MsVkxYzYMMtfriekP+wVz7z/eKtc8IPWMnt0909nPS7b0RHhBSQPuMSb3q79I/+f/9yAlDMTDtvhLwkrjKnFbN/SjHgGF5enmRy4DiseKIRnnpHl99TDHu69GuILLAY4zcyq69go=,iv:LIy9kFI/qUajcRdCpTKHvdW9HKylS2Nzr/j1DXvzscc=,tag:fM0X1dcbocAtAVAV5kO5NA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
