apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:kL+/AzfALC8YSg4K5m9g,iv:yW1HCt4erzOhEXW72eaaCstw4ppoT2OQZsjDr71a6es=,tag:zYZfVs+gCAlflSxRKJt0Sg==,type:str]
    SECRET_CIDR_LAN_V4: ENC[AES256_GCM,data:s//rhVIEp5LAFrHrzjo=,iv:GxR9Eqy3QTLY9D+elmvB87hcaCQNgdO2W4W5s5PUdeE=,tag:r1vyoY77C0lJ/zges78MEQ==,type:str]
    SECRET_CIDR_LAN_V6: ENC[AES256_GCM,data:AFYjytv5VIeV9r3JJSKwgo4mymIKkA==,iv:du52G4o9WDJp3c4oTzeZSJhnXx9L+uV32rr21b072NY=,tag:3vgQzk+9RvobsHSu9cDVNg==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:7sy1KOT4XDZuh8dmWt4=,iv:0OEhuQzvXv/boEuxioVq396fo580IH6vHt8uWYQxBDI=,tag:AF8Rn9kTLiErKZk+vfmomQ==,type:str]
    SECRET_LB_POOL_IPV4: ENC[AES256_GCM,data:+EnPzHEYWqh5xLwtUVY=,iv:26ZqnwpPgMgCT57C6UNt6k2uu2Kh+wWjkkng4Va/6ts=,tag:CmIsSCyajE8XuSfo0XdedQ==,type:str]
    SECRET_LB_POOL_IPV6: ENC[AES256_GCM,data:eB7nyAnFSxAliLPQF4J43K99mxSAYQW4,iv:WwF5dRSBOD/eF63x65eVu5ksQKYqibyBfNhxXZx5Uwo=,tag:n53+2cNHLjxNod5Da0zUbA==,type:str]
    SECRET_LB_IPV4: ENC[AES256_GCM,data:UoXkizUvdosgip4=,iv:/Or1StmxB0W19ypPSVCFWRnqsDR/VYkQOXceGEnOb/E=,tag:RwouAtohRqCf/X3bXabIHg==,type:str]
    SECRET_LB_IPV6: ENC[AES256_GCM,data:5uNaJ/oJjOXKvlIHkQsTCKP13KI=,iv:flKh9+MJP9qGHJ4dHDJ/W40U4iPCTZFZY/Htn6+iYAg=,tag:XV4OP2dBTvQ/ZoYdUzbvyw==,type:str]
    SECRET_NODE_IPV4: ENC[AES256_GCM,data:QqlUUcMkUnhR580O,iv:UZAm+hAnHUMOh1oqEbHLrWLxDV4C16hFrUfST9fZKJs=,tag:+J90aVoFFBlYSyfvjJuX4Q==,type:str]
    SECRET_NODE_IPV6: ENC[AES256_GCM,data:8Rof+JfVUWsvWGOu0Du0ajFzhBtm,iv:4piD2oM5Mu89w1UcR+0fOyP/6GL92z8zAMKEASeAfmM=,tag:BY9sFzZECD4NLlFhbJrh1w==,type:str]
    SECRET_DS418_IP: ENC[AES256_GCM,data:FMXE3TRGT9UmK9DP,iv:vL06OQmbmeMudTxUYY+C2ua6c9F5r+r/bJcxqXCsv84=,tag:SBqbZAjbL83AKI2fMdJ8hQ==,type:str]
    SECRET_DS418_VOLSYNC_PATH: ENC[AES256_GCM,data:xk588NtFmw72HeAlUAP2sByY/aUVP0RXvSXtMg7w5Q47c9TplazpQp4XklcJ,iv:dvQliXBGQsY+ba+eHTQJd/WYVtQmbYb83OEXW9i5wW4=,tag:DKwfeLeQ7BPJXEkMC9uBaA==,type:str]
    SECRET_DS416_IP: ENC[AES256_GCM,data:n2XcohYjcoMpY5cK,iv:Sn9JXCRAozdiBnOgLb6TfwXLeNP5TQVn5XikPMJ02xc=,tag:3pD6EvRvAbt6XZMaSwgkNg==,type:str]
sops:
    age:
        - recipient: age10mxrc4xzc0udh8ra304ftjnc6m3x3qfe60qulu8j9eqjhrgkns9qnk50up
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZYjFHd3hodnFVaG14Q0RK
            eUR3NHh4TXZ2U1BIck9BOXU4UG4wdzljWHdrCjJTb1p3d01ZSWxGNEtCMms0MG96
            N0R0MnFGczJ4M2NRNlFYZi9hVDY5L2sKLS0tIDA3TEM2TkNuNWRMM3JpUVR3dm8y
            SXdUSUFhN0c0ZWljOUovZHNVVGcvOVUKb3bl/Do5fX5SmCUMOmUVwYu+HQb0FCfH
            0mmi1whQL6Nb7SdwPD2IUlBSsI2r6E6n/OT3f+GmlOjTyysi+cgqbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-10T17:35:13Z"
    mac: ENC[AES256_GCM,data:hGAQH88hhGkxtajQQ1ByMjFkTzX9wuEvuCVpG/ItMuqSyW1/K4hYhrtxNgi0q6x3hN+FbPNybpsSRDWTbl9jYjHpltEhIi6GWc0S8i+ePbpNINLkMOx75pWjjvGglHa6XIhtk0lh7zxj7qc/RbAYylxmJ74k8eissiDQ+I3EnU0=,iv:Mv4AUtsZmF16pJ3dUBmsI2A8qaQsvfSoBYMu2DoA9X4=,tag:HTTg1BCf9/khZkyl7J3mkw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
