apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:kL+/AzfALC8YSg4K5m9g,iv:yW1HCt4erzOhEXW72eaaCstw4ppoT2OQZsjDr71a6es=,tag:zYZfVs+gCAlflSxRKJt0Sg==,type:str]
    SECRET_CIDR_LAN: ENC[AES256_GCM,data:aHfHwCCdwAKC+nfKrwU=,iv:M08olt3IBeH2pooCATkKgZVcQnACTiKGWAju2CEAppA=,tag:+ZBpKTW3MxJmk2O4NIQfjg==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:7sy1KOT4XDZuh8dmWt4=,iv:0OEhuQzvXv/boEuxioVq396fo580IH6vHt8uWYQxBDI=,tag:AF8Rn9kTLiErKZk+vfmomQ==,type:str]
    SECRET_LB_POOL_IPV4: ENC[AES256_GCM,data:+EnPzHEYWqh5xLwtUVY=,iv:26ZqnwpPgMgCT57C6UNt6k2uu2Kh+wWjkkng4Va/6ts=,tag:CmIsSCyajE8XuSfo0XdedQ==,type:str]
    SECRET_LB_POOL_IPV6: ENC[AES256_GCM,data:OeeNp5/tRfnFGwU=,iv:H9fJo08usjC3axJ9u/yiU1OIuUuA8kaK1xBEvzhWH1Y=,tag:Ok1CdXSsi6j8+z2pfOxIRQ==,type:str]
    SECRET_LB_IPV4: ENC[AES256_GCM,data:UoXkizUvdosgip4=,iv:/Or1StmxB0W19ypPSVCFWRnqsDR/VYkQOXceGEnOb/E=,tag:RwouAtohRqCf/X3bXabIHg==,type:str]
    SECRET_LB_IPV6: ENC[AES256_GCM,data:Ju72aZrpbA==,iv:L1Iql7K1VOIW0HoF3XE9PqPRZqf3CqAMUSzHb0fVL7A=,tag:yTJFcFj3vEIqHxaSfW2E9A==,type:str]
sops:
    age:
        - recipient: age10mxrc4xzc0udh8ra304ftjnc6m3x3qfe60qulu8j9eqjhrgkns9qnk50up
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZYjFHd3hodnFVaG14Q0RK
            eUR3NHh4TXZ2U1BIck9BOXU4UG4wdzljWHdrCjJTb1p3d01ZSWxGNEtCMms0MG96
            N0R0MnFGczJ4M2NRNlFYZi9hVDY5L2sKLS0tIDA3TEM2TkNuNWRMM3JpUVR3dm8y
            SXdUSUFhN0c0ZWljOUovZHNVVGcvOVUKb3bl/Do5fX5SmCUMOmUVwYu+HQb0FCfH
            0mmi1whQL6Nb7SdwPD2IUlBSsI2r6E6n/OT3f+GmlOjTyysi+cgqbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T22:15:02Z"
    mac: ENC[AES256_GCM,data:DEX7Jspeg4ezDjFrHn3ceJVfae2BxLFm37+e7tp8CMbriW+edFcB5UIv1skpl7fZhbxu1NDSuoj1FjNO6t94ZmnthZcqjiill44tEqCrmaCPybKOIHKw/AvXnJLg2LdyWEQb5xx8AH6a8cFcJK8acCznTmXea/+2kRyBUrXOjy0=,iv:gFXjieduJaXnHyBSw0FxpCsrzEE00u+EDxajY4bYU1M=,tag:sUCc37Jv2KVMncRA/NJOnQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
