apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:kL+/AzfALC8YSg4K5m9g,iv:yW1HCt4erzOhEXW72eaaCstw4ppoT2OQZsjDr71a6es=,tag:zYZfVs+gCAlflSxRKJt0Sg==,type:str]
sops:
  age:
    - recipient: age10mxrc4xzc0udh8ra304ftjnc6m3x3qfe60qulu8j9eqjhrgkns9qnk50up
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZYjFHd3hodnFVaG14Q0RK
        eUR3NHh4TXZ2U1BIck9BOXU4UG4wdzljWHdrCjJTb1p3d01ZSWxGNEtCMms0MG96
        N0R0MnFGczJ4M2NRNlFYZi9hVDY5L2sKLS0tIDA3TEM2TkNuNWRMM3JpUVR3dm8y
        SXdUSUFhN0c0ZWljOUovZHNVVGcvOVUKb3bl/Do5fX5SmCUMOmUVwYu+HQb0FCfH
        0mmi1whQL6Nb7SdwPD2IUlBSsI2r6E6n/OT3f+GmlOjTyysi+cgqbQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-28T12:36:03Z"
  mac: ENC[AES256_GCM,data:i/4QXT8en00kOf+kdRY8u2A45nzdOxhBLMHU9Ga+sZc27HKDhXYfRWf/pIGt4dvlRezOa73+vwIpIk2K4CNykaewjQ78FiqcU70+igJMlqHbd2b9r0NaGRqNIDaTw8h5Fe4Ssg1bkLzoRxhqOJsoprNwinyjeB8skJXZAnvFcOI=,iv:ESIFQzKiX77ymziMXmb6SefsAw/irP7TTz+cusS3VtY=,tag:k8nNwXtY3doUmV8YMcLBdw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
