apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:kL+/AzfALC8YSg4K5m9g,iv:yW1HCt4erzOhEXW72eaaCstw4ppoT2OQZsjDr71a6es=,tag:zYZfVs+gCAlflSxRKJt0Sg==,type:str]
    SECRET_CIDR_LAN: ENC[AES256_GCM,data:aHfHwCCdwAKC+nfKrwU=,iv:M08olt3IBeH2pooCATkKgZVcQnACTiKGWAju2CEAppA=,tag:+ZBpKTW3MxJmk2O4NIQfjg==,type:str]
sops:
    age:
        - recipient: age10mxrc4xzc0udh8ra304ftjnc6m3x3qfe60qulu8j9eqjhrgkns9qnk50up
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZYjFHd3hodnFVaG14Q0RK
            eUR3NHh4TXZ2U1BIck9BOXU4UG4wdzljWHdrCjJTb1p3d01ZSWxGNEtCMms0MG96
            N0R0MnFGczJ4M2NRNlFYZi9hVDY5L2sKLS0tIDA3TEM2TkNuNWRMM3JpUVR3dm8y
            SXdUSUFhN0c0ZWljOUovZHNVVGcvOVUKb3bl/Do5fX5SmCUMOmUVwYu+HQb0FCfH
            0mmi1whQL6Nb7SdwPD2IUlBSsI2r6E6n/OT3f+GmlOjTyysi+cgqbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T13:10:59Z"
    mac: ENC[AES256_GCM,data:ec46qArsTebZga+eaXZZoS8YKrvOYPCgd0T8cL4M8U9L+pYSI+wqtYh6LXiZReQlABbYixOgXm9JLHqQb+4d+knLa6YE/VHTzmzeEWMqGV+DHVvjQakqhbHOR9eTe3BL3y1ARiNVpQeWIy1pmsefaX1fIl3UMdyH27ncGe1zzCA=,iv:uWILDtZ8J0TEGtLAenLudhh8q8j1y4tNBRMYUpNs8kk=,tag:835Xd9e5B+0NxCpq0pijdw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
