---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./labelled-allow-ingress-cluster.yaml
  - ./labelled-allow-ingress-envoy-internal.yaml
  - ./labelled-allow-ingress-host.yaml
  - ./labelled-allow-ingress-internet.yaml
  - ./labelled-allow-ingress-kube-apiserver.yaml
  - ./labelled-allow-ingress-lan.yaml
  - ./labelled-deny-ingress.yaml
