---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ./s3-secret.sops.yaml
  - ./replication-destination.yaml
  - ./replication-source.yaml
  - ./pvc.yaml
