---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "${APP}-volsync-bootstrap"
spec:
  trigger:
    manual: restore-once
  restic:
    accessModes:
      - "${VOLSYNC_ACCESSMODES:-ReadWriteOnce}"
    cacheAccessModes:
      - "${VOLSYNC_CACHE_ACCESSMODES:-ReadWriteOnce}"
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:-1Gi}"
    cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:-openebs-lvmsc}"
    capacity: "${VOLSYNC_CAPACITY:-1Gi}"
    cleanupCachePVC: true
    cleanupTempPVC: true
    enableFileDeletion: true
    copyMethod: "${VOLSYNC_COPYMETHOD:-Snapshot}"
    moverSecurityContext:
      runAsUser: ${APP_UID:-2000}
      runAsGroup: ${APP_GID:-2000}
      fsGroup: ${APP_GID:-2000}
    repository: "${APP}-s3-volsync"
    storageClassName: "${VOLSYNC_STORAGECLASS:-openebs-lvmsc}"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:-openebs-lvmsc-snapclass}"
