---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: grafana-operator
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: grafana-operator
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: grafana-operator
  egress:
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/managed-by: grafana-operator
