services:
  dnscrypt:
    image: gists/dnscrypt-proxy:2.1.5
    restart: unless-stopped
    container_name: dnscrypt
    volumes:
      - "./dnscrypt-proxy.toml:/etc/dnscrypt-proxy/dnscrypt-proxy.toml:ro"
    networks:
      pihole_net:
  pihole:
    image: pihole/pihole:2026.02.0
    restart: unless-stopped
    container_name: pihole
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      # - "80:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      - "443:443/tcp"
      - "443:443/udp"
      # Uncomment the line below if you are using Pi-hole as your DHCP server
      #- "67:67/udp"
      # Uncomment the line below if you are using Pi-hole as your NTP server
      - "123:123/udp"
    environment:
      TZ: "Europe/Paris"
      # must match name of the service above
      FTLCONF_dns_upstreams: 'dnscrypt#5353'
      FTLCONF_dns_listeningMode: 'ALL'
      FTLCONF_dns_rateLimit_count: 10000
      FTLCONF_dns_rateLimit_interval: 30
    volumes:
      - '/home/podboy/docker/pihole:/etc/pihole'
    env_file:
      - secrets.sops.env
    cap_add:
      - CHOWN
      - SYS_TIME
      - SYS_NICE
    networks:
      pihole_net:
networks:
  pihole_net: