services:
  dnscrypt:
    image: gists/dnscrypt-proxy:2.1.5
    restart: unless-stopped
    container_name: dnscrypt
    volumes:
      - "./dnscrypt-proxy.toml:/etc/dnscrypt-proxy/dnscrypt-proxy.toml:ro"
    ports:
      - 127.0.0.1:5300:5353/tcp
      - 127.0.0.1:5300:5353/udp
  pihole:
    image: pihole/pihole:2026.02.0
    restart: unless-stopped
    container_name: &host pihole
    hostname: *host
    network_mode: host
    environment:
      TZ: "Europe/Paris"
      # must match name of the service above
      FTLCONF_dns_upstreams: '127.0.0.1#5300'
      FTLCONF_dns_listeningMode: 'ALL'
      FTLCONF_dns_rateLimit_count: 10000
      FTLCONF_dns_rateLimit_interval: 30
    volumes:
      - '/home/podboy/docker/pihole:/etc/pihole'
    env_file:
      - secrets.sops.env
    cap_add:
      - CHOWN
      - SYS_TIME
      - SYS_NICE
