services:
  dnscrypt:
    image: gists/dnscrypt-proxy:2.1.5
    restart: unless-stopped
    container_name: dnscrypt
    volumes:
      - "./dnscrypt-proxy.toml:/etc/dnscrypt-proxy/dnscrypt-proxy.toml:ro"
    ports:
      - "127.0.0.1:5353:5353/udp"
      - "127.0.0.1:5353:5353/tcp"
      - "[::]:5353:5353/udp"
      - "[::]:5353:5353/tcp"
  pihole:
    image: pihole/pihole:2026.02.0
    restart: unless-stopped
    container_name: pihole
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "80:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      - "443:443/tcp"
      # Uncomment the line below if you are using Pi-hole as your DHCP server
      #- "67:67/udp"
      # Uncomment the line below if you are using Pi-hole as your NTP server
      - "123:123/udp"
    environment:
      TZ: "Europe/Paris"
      # must match name of the service above
      FTLCONF_dns_upstreams: 'dnscrypt'
      FTLCONF_dns_listeningMode: 'ALL'
    volumes:
      - './etc-pihole:/etc/pihole'
    env_file:
      - secrets.sops.env
    cap_add:
      - CHOWN
      - SYS_TIME
      - SYS_NICE