- name: install unattended-upgrades
  package:
    name:
      - unattended-upgrades
    state: latest

- name: copy config
  template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
  notify: restart unattended-upgrades