all:
  children:
    # distros
    raspbian:
      hosts:
        PiHoleGamma:
          ansible_host: 192.168.0.2
    rocky:
      hosts:
        LabDMZ:
          ansible_host: 192.168.0.36
        PiHoleBeta:
          ansible_host: 192.168.0.3
    proxmox:
      hosts:
        Akame:
          ansible_ssh_user: root
          ansible_host: 192.168.0.5
        Lynka:
          ansible_ssh_user: root
          ansible_host: 192.168.0.6
  
    docker:
      hosts:
        PiHoleBeta:
        PiHoleGamma:
        LabDMZ:

    dns_server:
      hosts:
        PiHoleBeta:
        PiHoleGamma:

    nut:
      hosts:
        Akame:
        PiHoleGamma: