all:
  children:
    # distros
    rocky:
      hosts:
        LabDMZ:
          ansible_host: 192.168.0.36
        PiHoleAlpha:
          ansible_host: 192.168.0.2
        PiHoleBeta:
          ansible_host: 192.168.0.3
        PiHoleGamma:
          ansible_host: 192.168.0.7
    proxmox:
      hosts:
        Akame:
          ansible_ssh_user: root
          ansible_host: 192.168.0.5
        Lynka:
          ansible_ssh_user: root
          ansible_host: 192.168.0.6
  
    docker:
      hosts:
        PiHoleAlpha:
        PiHoleBeta:
        PiHoleGamma:
        LabDMZ:

    dns_server:
      hosts:
        PiHoleAlpha:
        PiHoleBeta:
        PiHoleGamma: