---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: kube-state-metrics-kubelet
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: metrics-server
  egress:
    - toEntities:
        - host
      toPorts:
        - ports:
            # kubeapi
            - port: "10250"
              protocol: TCP
            - port: "10250"
              protocol: UDP
